### ISSUE TITLE
Dependency errors!! Map drawing

### ISSUE THREAD

**Issue by Idzikowski-Casey** [EarthCubeGeochron/Sparrow#102]
<img width="825" alt="Screen Shot 2021-04-15 at 11 36 51 AM" src="https://user-images.githubusercontent.com/65414051/114897044-dfebb880-9dde-11eb-9f72-ac56a2851a6c.png">

I have been getting this error when running `sparrow up`, I believe the error is coming from conflicting dependencies in the `@urbica/react-map-gl`, `@urbica/react-map-gl-draw` and our downloaded versions of `mapbox-gl`. Since the components we use these libraries for a small and simple, I think it will be better to remove these third-party libraries and use `mapbox-gl` and `mapbox-gl-draw` directly.  It will also reduce the codebase size.

**Comment by davenquinn** [comment]
The core problem here is that we upgraded to `npm` v7 in the Sparrow frontend component recently, which is more stringent about ensuring that peer dependencies match.

Why don't you update `react-map-gl` to version `5.x` as asked, or pin the `react-map-gl-draw` to an older version that works with the 4.x series? Or you can update `mapbox-gl`. _Or_ you can add the `--legacy-peer-deps` command to the `npm install` to skip the strict check.

Although removing the React wrappers from `mapbox-gl` seems tempting, we will have to re-implement much of their internal logic ourselves anyway. This will be time-consuming and not improve things much from a user perspective.
