### ISSUE TITLE
Search issue Map view add samples

### ISSUE THREAD

**Issue by thefallingduck** [EarthCubeGeochron/Sparrow#125]
Running local instance and attempting to add samples using map view because geological map in reference is only way to get location. Attempted to use add via geological map but the search seems limited to the list that shows up in the short drop down menu.

**Comment by thefallingduck** [comment]
The add sample search should also allow filters by project.

**Comment by thefallingduck** [comment]
Add samples to location in Map view is populated by some list not associated with the API. Both Cosmos and SIMS servers have the same list of samples. I think this is an issue?

![image](https://user-images.githubusercontent.com/11468682/118161372-1c620280-b3e5-11eb-91fe-1938cb4ed960.png)

**Comment by Idzikowski-Casey** [comment]
I have a local branch that has fixed this! About a week old. I'll set a PR to develop today or tomorrow.
