### ISSUE TITLE
Auto backup

### ISSUE THREAD

**Issue by thefallingduck** [EarthCubeGeochron/Sparrow#129]
Need to have an autobackup feature for database so we can edit using QGIS etc. Useful for development and a few other things.

@davenquinn has some code that exists already.

**Comment by davenquinn** [comment]
This exists now in Sparrow v2.0.0.beta7! See [the README](https://github.com/EarthCubeGeochron/Sparrow/tree/main/services/backup-database) for now. We should add it to the documentation.

**Comment by davenquinn** [comment]
Also, it would be good to start testing this on some of our production instances.
