### ISSUE TITLE
Geological entity name breaks - Sample metadata editing

### ISSUE THREAD

**Issue by thefallingduck** [EarthCubeGeochron/Sparrow#130]
The geological entity search box breaks after typing and deleting characters. Switches to "Add new" option too quickly then. This is likely to lead to many more varieties of geological unit when we want to keep formations, etc. highlighted.

<img width="480" alt="Screen Shot 2021-05-07 at 11 09 36 AM" src="https://user-images.githubusercontent.com/11468682/117478817-3d2de200-af25-11eb-9ea9-22b8a7b1e9f4.png">

**Comment by Idzikowski-Casey** [comment]
This was a good catch!! I have figured out the issue! The breaking occured when the query string matched no item in the list, which is list of names coming from the Macrostrat API. What was happening was, I was perfoming changing the query string for the API call at the wrong callback inside Blueprintjs's internal functions. I was calling it at the `itemPredicate` function which is what matches the query string to an item in the list. But when the list is empty this function just stops, and so the query string was not updating, and therefore no API call was being made.

I've changed it to the correct callback, `onQueryChange` and it works like it's supposed to now.
