### ISSUE TITLE
Panels not updating when selecting new sample

### ISSUE THREAD

**Issue by thefallingduck** [EarthCubeGeochron/Sparrow#133]
Upon clicking a new sample name from the left panel, some entries in the right panel do not update. These include Geological Context and Depth. Although this can be good for putting in multiple samples on a project, the blank field for Geological Context is confusing. See the grey box below.
<img width="1361" alt="Screen Shot 2021-05-07 at 12 36 44 PM" src="https://user-images.githubusercontent.com/11468682/117487770-23929780-af31-11eb-849c-e655a3ee57f3.png">

**Comment by Idzikowski-Casey** [comment]
For now, I'll have it so that if you resubmit the Geologic Context it doesn't give the empty box but returns the same geo context. That way, if someone has multiple samples they can easily make them all the same context.
