### ISSUE TITLE
Failure to add new publication

### ISSUE THREAD

**Issue by thefallingduck** [EarthCubeGeochron/Sparrow#134]
New publication can be added to this view, but does not write to database.

<img width="957" alt="Screen Shot 2021-05-07 at 2 45 55 PM" src="https://user-images.githubusercontent.com/11468682/117500925-f18a3100-af42-11eb-8845-d7a4af7cdc42.png">

**Comment by Idzikowski-Casey** [comment]
this now a part of a separate issue. #160
