### ISSUE TITLE
Failure to add new researcher

### ISSUE THREAD

**Issue by thefallingduck** [EarthCubeGeochron/Sparrow#135]
New researcher can be created in interface but is not written to database and saved.

Adding researcher in database, linking to project, and saving in interface also doesn't update database.

<img width="957" alt="Screen Shot 2021-05-07 at 2 48 45 PM" src="https://user-images.githubusercontent.com/11468682/117501186-56458b80-af43-11eb-9ca8-dcebdd1cfdf5.png">

**Comment by Idzikowski-Casey** [comment]
this now envolped in a separte issue. #160
