### ISSUE TITLE
Search using map is broken

### ISSUE THREAD

**Issue by thefallingduck** [EarthCubeGeochron/Sparrow#137]
Doesn't work on either the Sample or Project search in Admin. Map is not populated with the samples or projects that have geographic coordinates.

Search should also be available outside of Admin mode if possible?

**Comment by Idzikowski-Casey** [comment]
As for populating the map with locations... I have a local branch where I experimented with it as a new feature. It's a little slow right now and basically, the projects are inheriting their location filterability directly from samples now anyways. But we do have this added feature in the works.
