### ISSUE TITLE
Backend API use for data import

### ISSUE THREAD

**Issue by thefallingduck** [EarthCubeGeochron/Sparrow#150]
This isn't strictly an issue and I know we'll solve the API security things shortly. Mostly notes for next week when I get back to it.

Merged `develop` into `WiscSIMS-fixes` and attempted to import data using the new `instrument_session` table. This also enabled API security. When a user was made and logged into the frontend, the `PUT()` into the database still worked using backend:5000, but the API `GET()` did not. Currently for importing, I need to create a unique key for the `instrument_session` and tie that to the `session` input, but can't get that key because of `GET()` security.

**Comment by thefallingduck** [comment]
I think this is completely solved with the new API security measures that @Idzikowski-Casey added, but will do some more testing before closing it out. This was happening on API V1.

**Comment by davenquinn** [comment]
Seems like we have fixed this one. Huzzah!
