### ISSUE TITLE
Viewing projects in frontend causes catalog to crash

### ISSUE THREAD

**Issue by Peter-E-Martin** [EarthCubeGeochron/Sparrow#193]
![frontend_err](https://user-images.githubusercontent.com/76170591/130294412-55362fe8-c9d2-40ae-a715-69fbef470d79.PNG)
![frontend_err_console1](https://user-images.githubusercontent.com/76170591/130294413-aecd9a02-3025-4670-b1f7-c974bf7e14c2.PNG)
![frontend_err_console2](https://user-images.githubusercontent.com/76170591/130294414-413bdd6f-ae7f-40a8-8628-4fd332252750.PNG)
In the public-facing catalog, if the projects tab is selected, the data become unviewable

**Comment by Idzikowski-Casey** [comment]
Okay, found the issue. Null values were being passed for `publication` and `sample` prop the `ProjectInfoLink` component and the default props don't handle `null` only `undefinded`.
