### ISSUE TITLE
Searching for projects by name returns no results

### ISSUE THREAD

**Issue by davenquinn** [EarthCubeGeochron/Sparrow#194]
On the latest `develop` branch, searching for projects by name does not return any results, even for straightforward queries.

https://user-images.githubusercontent.com/1537910/130298213-07627206-a81a-4c0b-9b47-0acd7c3e37ba.mov

This appears to relate to the recent changes to open-search functionality (#186).

**Comment by davenquinn** [comment]
I assume this can be replicated using the API? If so, we should create some tests.

**Comment by Idzikowski-Casey** [comment]
@davenquinn there is a testing class for the Open-Search in this version of `develop` [here](https://github.com/EarthCubeGeochron/Sparrow/blob/develop/backend/sparrow/open_search/test_open_search.py). This morning I made a new test to try and recreate the issue you are seeing here. That test can be found in [this PR](https://github.com/EarthCubeGeochron/Sparrow/commit/bff7279e34178f7343cd743b09399574807d1aad). 

All of the tests are passing.. Perhaps there is another reason for the projects not being returned. If the API call, in the `network` tab of dev tools, is returning an empty array then the database probably needs to be reinitialized. Perhaps the current version didn't get the trigger updates.

**Comment by davenquinn** [comment]
Fixed (temporarily) by #198. We'll want to create a more permanent fix eventually; I've created issue #199 for that.
