### ISSUE TITLE
__init__() got an unexpected keyword argument "disable_buffering"

### ISSUE THREAD

**Issue by Idzikowski-Casey** [EarthCubeGeochron/Sparrow#204]
<img width="764" alt="Screen Shot 2021-09-01 at 1 39 34 PM" src="https://user-images.githubusercontent.com/65414051/131728652-3e6bd7ff-03b9-4529-9512-9dbb1b4f2f71.png">
<img width="720" alt="Screen Shot 2021-09-01 at 1 39 41 PM" src="https://user-images.githubusercontent.com/65414051/131728659-099bfc2b-9f60-47fb-a453-53aecd690cda.png">

**Comment by davenquinn** [comment]
This seems to be a major issue only encountered in the bundled Sparrow CLI.

**Comment by davenquinn** [comment]
This is an upstream issue reported _today_ in docker-compose: https://github.com/docker/compose/issues/8499. I'll implement the workaround and rebuild...
