### ISSUE TITLE
HTTP_TIMEOUT issue Ubuntu server

### ISSUE THREAD

**Issue by thefallingduck** [EarthCubeGeochron/Sparrow#21]
`frontend_1   | [Browsersync] Access URLs:
frontend_1   |  ----------------------------------
frontend_1   |           UI: http://localhost:3001
frontend_1   |  ----------------------------------
frontend_1   |  UI External: http://localhost:3001
frontend_1   |  ----------------------------------
ERROR: An HTTP request took too long to complete. Retry with --verbose to obtain debug information.
If you encounter this issue regularly because of slow network conditions, consider setting COMPOSE_HTTP_TIMEOUT to a higher value (current value: 60).`

Server timeout issue on CS Ubuntu server version of Sparrow-WiscSIMS. The `sparrow down` command does not flag any errors.

**Comment by davenquinn** [comment]
Perhaps this is related to docker/compose#3633 in which case requiring a new (~1.25) version of docker compose might be the best option.

**Comment by davenquinn** [comment]
Has this been a problem lately, @thefallingduck ? I suspect it is fixed by bundling our own docker-compose.
