### ISSUE TITLE
Github CI for Sparrow Tests fails because env variable is not available.

### ISSUE THREAD

**Issue by Idzikowski-Casey** [EarthCubeGeochron/Sparrow#216]
Locally all tests path, but in Github's CI for sparrow tests, during setup the app fails to build because of new changes to CLI made in PR #209. The `SPARROW_CONFIG_DIR`, which I believe is set automatically locally based on the location of `sparrow_config.sh`, is non-existent in the CI and therefore fails during building.
<img width="1081" alt="Screen Shot 2021-09-26 at 1 21 09 PM" src="https://user-images.githubusercontent.com/65414051/134805553-a530bfee-84a7-4902-8323-000bd46bb162.png">

**Comment by davenquinn** [comment]
This isn't an issue with Sparrow unless it moves beyond the PR stage
