### ISSUE TITLE
Error on Sparrow Up

### ISSUE THREAD

**Issue by kuehnstephenc** [EarthCubeGeochron/Sparrow#242]
MacBook-Pro-3:~ stephenkuehn$ SPARROW_SECRET_KEY=TemporaryKey sparrow up
broker uses an image, skipping
db uses an image, skipping
gateway uses an image, skipping
Building backend
[+] Building 1.5s (18/18) FINISHED                                                                                                                                            
 => [internal] load build definition from Dockerfile                                                                                                                     0.0s
 => => transferring dockerfile: 34B                                                                                                                                      0.0s
 => [internal] load .dockerignore                                                                                                                                        0.0s
 => => transferring context: 34B                                                                                                                                         0.0s
 => [internal] load metadata for ghcr.io/earthcubegeochron/sparrow/backend-base:2.0                                                                                      1.4s
 => [main  1/12] FROM ghcr.io/earthcubegeochron/sparrow/backend-base:2.0@sha256:46789182dde48c1be1f07a82172abb905139b445af64032602fe3073ae2a697f                         0.0s
 => [internal] load build context                                                                                                                                        0.0s
 => => transferring context: 19.45kB                                                                                                                                     0.0s
 => importing cache manifest from ghcr.io/earthcubegeochron/sparrow/backend:2.0.0.beta17                                                                                 0.0s
 => CACHED [main  2/12] RUN apt update && apt install -y git                                                                                                             0.0s
 => CACHED [main  3/12] COPY ./requirements.txt /install/requirements.txt                                                                                                0.0s
 => CACHED [main  4/12] RUN pip install --no-cache -r /install/requirements.txt                                                                                          0.0s
 => CACHED [main  5/12] COPY ./docker.cfg /config/docker.cfg                                                                                                             0.0s
 => CACHED [main  6/12] RUN git clone https://github.com/davenquinn/sadisplay.git /ext/sadisplay   && pip install -e /ext/sadisplay                                      0.0s
 => CACHED [main  7/12] COPY ./docker-scripts/* /bin/                                                                                                                    0.0s
 => CACHED [main  8/12] RUN mkdir /app                                                                                                                                   0.0s
 => CACHED [main  9/12] WORKDIR /app                                                                                                                                     0.0s
 => CACHED [main 10/12] COPY ./ /app/                                                                                                                                    0.0s
 => CACHED [main 11/12] RUN pip install -e utils && pip install -e .                                                                                                     0.0s
 => CACHED [main 12/12] RUN SPARROW_SECRET_KEY=test /app/sparrow/__main__.py get-cli-info > /run/cli-info.json                                                           0.0s
 => exporting to image                                                                                                                                                   0.0s
 => => exporting layers                                                                                                                                                  0.0s
 => => writing image sha256:6310c25337007c745a72301fc14854d3407716a17474a106877941307adbcdbb                                                                             0.0s
 => => naming to ghcr.io/earthcubegeochron/sparrow/backend:2.0.0.beta17                                                                                                  0.0s
Building frontend
[+] Building 1.6s (8/8) FINISHED                                                                                                                                              
 => [internal] load build definition from Dockerfile                                                                                                                     0.0s
 => => transferring dockerfile: 34B                                                                                                                                      0.0s
 => [internal] load .dockerignore                                                                                                                                        0.0s
 => => transferring context: 34B                                                                                                                                         0.0s
 => [internal] load metadata for docker.io/library/node:14                                                                                                               1.5s
 => importing cache manifest from ghcr.io/earthcubegeochron/sparrow/frontend:2.0.0.beta17                                                                                0.0s
 => [base 1/3] FROM docker.io/library/node:14@sha256:167d0a4af6b4e0d0769086b871a36c25faed75b72705144cabbda70466cc0d8e                                                    0.0s
 => => resolve docker.io/library/node:14@sha256:167d0a4af6b4e0d0769086b871a36c25faed75b72705144cabbda70466cc0d8e                                                         0.0s
 => CACHED [base 2/3] RUN npm install -g webpack webpack-cli nodemon                                                                                                     0.0s
 => CACHED [base 3/3] WORKDIR /app                                                                                                                                       0.0s
 => exporting to image                                                                                                                                                   0.0s
 => => exporting layers                                                                                                                                                  0.0s
 => => writing image sha256:6e02501fac48b655931cf743489d392af17f936f01afacad9f072bcb6f840bb2                                                                             0.0s
 => => naming to ghcr.io/earthcubegeochron/sparrow/frontend:2.0.0.beta17                                                                                                 0.0s
Building worker
[+] Building 0.4s (18/18) FINISHED                                                                                                                                            
 => [internal] load build definition from Dockerfile                                                                                                                     0.0s
 => => transferring dockerfile: 34B                                                                                                                                      0.0s
 => [internal] load .dockerignore                                                                                                                                        0.0s
 => => transferring context: 34B                                                                                                                                         0.0s
 => [internal] load metadata for ghcr.io/earthcubegeochron/sparrow/backend-base:2.0                                                                                      0.2s
 => [main  1/12] FROM ghcr.io/earthcubegeochron/sparrow/backend-base:2.0@sha256:46789182dde48c1be1f07a82172abb905139b445af64032602fe3073ae2a697f                         0.0s
 => [internal] load build context                                                                                                                                        0.0s
 => => transferring context: 19.45kB                                                                                                                                     0.0s
 => importing cache manifest from ghcr.io/earthcubegeochron/sparrow/backend:2.0.0.beta17                                                                                 0.0s
 => CACHED [main  2/12] RUN apt update && apt install -y git                                                                                                             0.0s
 => CACHED [main  3/12] COPY ./requirements.txt /install/requirements.txt                                                                                                0.0s
 => CACHED [main  4/12] RUN pip install --no-cache -r /install/requirements.txt                                                                                          0.0s
 => CACHED [main  5/12] COPY ./docker.cfg /config/docker.cfg                                                                                                             0.0s
 => CACHED [main  6/12] RUN git clone https://github.com/davenquinn/sadisplay.git /ext/sadisplay   && pip install -e /ext/sadisplay                                      0.0s
 => CACHED [main  7/12] COPY ./docker-scripts/* /bin/                                                                                                                    0.0s
 => CACHED [main  8/12] RUN mkdir /app                                                                                                                                   0.0s
 => CACHED [main  9/12] WORKDIR /app                                                                                                                                     0.0s
 => CACHED [main 10/12] COPY ./ /app/                                                                                                                                    0.0s
 => CACHED [main 11/12] RUN pip install -e utils && pip install -e .                                                                                                     0.0s
 => CACHED [main 12/12] RUN SPARROW_SECRET_KEY=test /app/sparrow/__main__.py get-cli-info > /run/cli-info.json                                                           0.0s
 => exporting to image                                                                                                                                                   0.0s
 => => exporting layers                                                                                                                                                  0.0s
 => => writing image sha256:6310c25337007c745a72301fc14854d3407716a17474a106877941307adbcdbb                                                                             0.0s
 => => naming to ghcr.io/earthcubegeochron/sparrow/backend:2.0.0.beta17                                                                                                  0.0s
srcroot_db_1 is up-to-date
srcroot_broker_1 is up-to-date
srcroot_backend_1 is up-to-date
srcroot_worker_1 is up-to-date
All containers built successfully.

Starting the Sparrow application!
Some containers are already running and up to date: 
  db, broker, worker, backend
To fully restart Sparrow, run sparrow restart or sparrow up --force-recreate.

Following container logs
- Press Ctrl+c to exit (Sparrow will keep running).
- Sparrow can be stopped with the sparrow down command.

Starting db       ... done
Starting broker   ... done
Starting worker   ... done
Starting backend  ... done
Starting frontend ... error
Starting gateway  ... error

ERROR: for frontend  Cannot start service frontend: OCI runtime create failed: container_linux.go:380: starting container process caused: process_linux.go:545: container init caused: rootfs_linux.go:76: mounting "/host_mnt/Users/stephenkuehn/.sparrow/opt/srcroot/frontend/default-content" to rootfs at "/app/site-content" caused: mkdir /var/lib/docker/overlay2/13a1a86d586b3b0abf173b593f5fb16bf8c3c850b996ad8513a2a5eeaf6a0b83/merged/app/site-content: operation not permitted: unknown
Attaching to srcroot_gateway_1, srcroot_frontend_1, srcroot_worker_1, srcroot_backend_1, srcroot_broker_1, srcroot_db_1
srcroot_gateway_1 exited with code 0
srcroot_frontend_1 exited with code 128

**Comment by davenquinn** [comment]
This bug was encountered by several people (including myself) running the default Sparrow instance. A few points:

- This is troubling, as it seems to be a difficult to diagnose Docker volume-mounting error
- It seems to only happen when working on some systems (maybe it's another Mac thing like #210 ?)
- It can be worked around for the time being by setting `export SPARROW_ENV="production"` in the configuration. 

We should probably set a production configuration for the frontend container by default if running from the bundled version (or maybe overall)? That would close off a whole class of volume mounting errors, potentially...
