### ISSUE TITLE
Error on WiscSIMS batch import using API locally

### ISSUE THREAD

**Issue by thefallingduck** [EarthCubeGeochron/Sparrow#26]
```
db_1         | 	SQL statement "SELECT pgmemento.log_table_event(txid_current(), TG_TABLE_NAME, TG_TABLE_SCHEMA, TG_OP)"
db_1         | 	PL/pgSQL function pgmemento.log_transaction() line 3 at PERFORM
db_1         | 2020-06-02 20:22:12.832 UTC [90] STATEMENT:  INSERT INTO datum (analysis, type, value, error, is_bad, is_accepted) VALUES (NULL, 1, 2, NULL, NULL, NULL) RETURNING datum.id
db_1         | 2020-06-02 20:22:16.301 UTC [91] ERROR:  out of shared memory
db_1         | 2020-06-02 20:22:16.301 UTC [91] HINT:  You might need to increase max_locks_per_transaction.
```
Response from sparrow. Potentially a docker shared memory error. Here: https://www.cybertec-postgresql.com/en/postgresql-you-might-need-to-increase-max_locks_per_transaction/

Preceded by...
`$error
$error$type
[1] "marshmallow.exceptions.ValidationError"
$error$code
[1] 400
$error$messages
$error$messages$analysis
$error$messages$analysis$`39`
$error$messages$analysis$`39`$datum
$error$messages$analysis$`39`$datum$`1`
$error$messages$analysis$`39`$datum$`1`$value
$error$messages$analysis$`39`$datum$`1`$value[[1]]
[1] "Not a valid number."
$error
$error$type
[1] "marshmallow.exceptions.ValidationError"
$error$code
[1] 400
$error$messages
$error$messages$analysis
$error$messages$analysis$`3`
$error$messages$analysis$`3`$datum
$error$messages$analysis$`3`$datum$`1`
$error$messages$analysis$`3`$datum$`1`$value
$error$messages$analysis$`3`$datum$`1`$value[[1]]
[1] "Not a valid number."
$error$messages$analysis$`39`
$error$messages$analysis$`39`$datum
$error$messages$analysis$`39`$datum$`1`
$error$messages$analysis$`39`$datum$`1`$value
$error$messages$analysis$`39`$datum$`1`$value[[1]]
[1] "Not a valid number."
$error
$error$type
[1] "marshmallow.exceptions.ValidationError"
$error$code
[1] 400
$error$messages
$error$messages$analysis
$error$messages$analysis$`39`
$error$messages$analysis$`39`$datum
$error$messages$analysis$`39`$datum$`1`
$error$messages$analysis$`39`$datum$`1`$value
$error$messages$analysis$`39`$datum$`1`$value[[1]]
[1] "Not a valid number."
$error
$error$type
[1] "marshmallow.exceptions.ValidationError"
$error$code
[1] 400
$error$messages
$error$messages$analysis
$error$messages$analysis$`39`
$error$messages$analysis$`39`$datum
$error$messages$analysis$`39`$datum$`1`
$error$messages$analysis$`39`$datum$`1`$value
$error$messages$analysis$`39`$datum$`1`$value[[1]]
[1] "Not a valid number."`

and
```

`{html_document}
<html>
[1] <head>\n<meta http-equiv="Content-Type" content="text/html; charset=UTF-8 ...
[2] <body style="background-color: #fff">\n    <div class="debugger">\n<h1>sq ...
{html_document}
<html>
[1] <head>\n<meta http-equiv="Content-Type" content="text/html; charset=UTF-8 ...
[2] <body style="background-color: #fff">\n    <div class="debugger">\n<h1>sq ...
{html_document}
<html>
[1] <head>\n<meta http-equiv="Content-Type" content="text/html; charset=UTF-8 ...
[2] <body style="background-color: #fff">\n    <div class="debugger">\n<h1>sq ...
{html_document}
<html>
[1] <head>\n<meta http-equiv="Content-Type" content="text/html; charset=UTF-8 ...
[2] <body style="background-color: #fff">\n    <div class="debugger">\n<h1>sq ...`
```

**Comment by davenquinn** [comment]
This is likely because large imports are happening without closing transactions, somehow. We can probably create a test to replicate the issue that imports a really long list of stuff and tries to break the database system. This will tell us whether the proper fix is to improve the import process or to tweak settings on the database.

**Comment by thefallingduck** [comment]
Attempted using `Sys.sleep(15)` after `PUT()` in R batch importer, but still returning max_locks_per_transaction error.

**Comment by thefallingduck** [comment]
Looked at this and created a passing test that is due to the fact that python is waiting on the PUT request.

Changes are here -> c7287af

**Comment by Idzikowski-Casey** [comment]
It appears this was resolved.
