### ISSUE TITLE
Some platforms do not support `docker-compose exec -T`

### ISSUE THREAD

**Issue by davenquinn** [EarthCubeGeochron/Sparrow#29]
Recent Ubuntu with the `apt`-installable version of Docker-Compose does not support `docker-compose exec -T` to allow multiline scripts to be run within the container. This fails silently without running any commands. It causes silent failures in `sparrow db-import`.

For now we can fix by splitting commands up into multiple `sparrow compose exec` calls into the container. However, eventually, we could fix this by bundling a fixed `docker-compose` version into our executable `sparrow` package (#28).

**Comment by davenquinn** [comment]
This is addressed for the `sparrow db-import` command, but there may be other commands with the same issue.

**Comment by thefallingduck** [comment]
Could also be causing #31 ?
