### ISSUE TITLE
sparrow create-user

### ISSUE THREAD

**Issue by thefallingduck** [EarthCubeGeochron/Sparrow#31]
Attempt to create a user using `sparrow create-user` with sparrow running returns...

the same thing as `docker-compose --help`

**Running on**

Ubuntu 18.04.4 LTS
Welcome to Ubuntu 18.04.4 LTS (GNU/Linux 4.15.0-106-generic x86_64)

Doesn't happen on local mac version although might be different sparrow branch (updates on ubuntu vs master for Sparrow-WiscSIMS on mac).

**Comment by davenquinn** [comment]
Yep, this is basically the same issue. I'm working on a fix now. The `sparrow` command is totally choking on this before it can run anything.

**Comment by davenquinn** [comment]
There was another problem with this on Ubuntu that was fixed in resolving #29 more fully with #32.
