### ISSUE TITLE
API route: week, month, year summary and date range for sessions

### ISSUE THREAD

**Issue by cambro** [EarthCubeGeochron/Sparrow#5]
API should have following routes/paramterizations:
time_metrics (general report of weekly, monthly, yearly report)
?begin=2019-01-01&end=2019-01-05

**Comment by davenquinn** [comment]
The latter part of this feature request is now integrated into the `develop` branch.

Any date column in a view, materialized view, or table will now accept a `<x>_start` and `<x>_end` API parameter. So now `analysis`, `datum`, `age_datum`, etc., all have a `date_start` and `date_end`. The format must be `2017-01-31` or similar, and the dates must be in order.

The appropriate edit widgets for this are now in the API explorer.

**Comment by Idzikowski-Casey** [comment]
This functionality now exists on the `apiv2` filters.
