### ISSUE TITLE
Data importer error

### ISSUE THREAD

**Issue by yeshancqcq** [EarthCubeGeochron/Sparrow#54]
When re-upload the data in the spreadsheet, an importer error shows up. @davenquinn Did you change the location of /cosmo-importer/cosmo_importer/__main__.py in the Sparrow config?

![image](https://user-images.githubusercontent.com/11675281/92287656-02743580-eed0-11ea-96eb-0915a03a045a.png)

**Comment by davenquinn** [comment]
This is an issue with using the Mac version of `readlink` instead of the GNU version for the testing Sparrow command. It should not happen, and has been fixed in the latest `develop` branch. You will have to run `make install-dev` again after updating.
