### ISSUE TITLE
Cannot log in on the cosmo instance after updating to the newer sparrow core

### ISSUE THREAD

**Issue by yeshancqcq** [EarthCubeGeochron/Sparrow#70]
And unable to run sparrow create-user either.

**Comment by davenquinn** [comment]
Any more details on how (in particular) `sparrow create-user` fails? Did you run `make install-dev` to update the command-line installation? Is the user still in the database?

**Comment by davenquinn** [comment]
@yeshancqcq can you post an update including the need to fix documentation?

**Comment by yeshancqcq** [comment]
Solved by upgrading the command line tools for code and then make install-dev
