### ISSUE TITLE
Syntax error when running sparrow in command lines

### ISSUE THREAD

**Issue by yeshancqcq** [EarthCubeGeochron/Sparrow#81]
This syntax error, previously assumed to be caused by older versions of Python, still exists after upgrading the Python to the latest version:

![image](https://user-images.githubusercontent.com/11675281/112554441-4fe4c100-8d94-11eb-84c5-68fbcdbaef2e.png)

**Comment by davenquinn** [comment]
Uhhh...interesting. My only thought is that it is somehow being run using Python 2, or referencing an older version. Can you run `make clean` followed by `make install` to see if that solves any problems?

**Comment by yeshancqcq** [comment]
This issue has been solved by running `make clean`, and then `make`. The next time the terminal is started, `make install-dev` can be run.
