### ISSUE TITLE
Long titles on map page overflow toolbar

### ISSUE THREAD

**Issue by davenquinn** [EarthCubeGeochron/Sparrow#83]
<img width="361" alt="Screen Shot 2021-03-26 at 1 31 19 AM" src="https://user-images.githubusercontent.com/1537910/112591911-12535880-8dd3-11eb-83bc-ea3fc5a98cb2.png">

Options:
- Make toolbar expand if title is long
- Truncate overflowing title (use `overflow-truncate` or something to add `...`)
- Add short title option somewhere

Or a combination

**Comment by Idzikowski-Casey** [comment]
closed [here](https://github.com/EarthCubeGeochron/Sparrow/pull/88/commits/fbe23112ac4e73b594534c0d21ef072a698aa535)
