### ISSUE TITLE
"Open search" view

### ISSUE THREAD

**Issue by davenquinn** [EarthCubeGeochron/Sparrow#93]
There should be an "open search" view prominently in the admin section. This should be quick and pull back samples, sessions, and projects. It should search across a set of fields that we can easily change, but would ideally include paper name, researcher name, project name, sample name, etc. It should be based on raw SQL and be quick as a first-class concern! We can worry about filterability later

**Comment by Idzikowski-Casey** [comment]
I will start this on branch `open-search`.
